###
#Copyright (c) 2021 Fundacion Jala.
#
#This software is the confidential and proprietary information of Fundacion Jala
#("Confidential Information"). You shall not disclose such Confidential
#Information and shall use it only in accordance with the terms of the
#license agreement you entered into with Fundacion Jala
##

# version de docker compose que utilizaremos para compilar este archivo
version: '3.1'
# servicios=contenedores que crearemos con docker compose
services:
 # primer servicio=contenedor
 db:
   # nombre del contenedor
   container_name: micontenedormysql
   # imagen que usaremos
   image: mysql
   # reinicia el contenedor si algo sale mal
   restart: always
   # puertos
   ports:
     - 9090:3306
   # variables de entorno
   environment:
     MYSQL_ROOT_PASSWORD: root
     MYSQL_DATABASE: jalaconverter