###
#Copyright (c) 2021 Fundacion Jala.
#
#This software is the confidential and proprietary information of Fundacion Jala
#("Confidential Information"). You shall not disclose such Confidential
#Information and shall use it only in accordance with the terms of the
#license agreement you entered into with Fundacion Jala
##

# version docker for compile
version: '3.1'
# services = containers that we will create with docker compose
services:
 # first service for our container
 db:
   # name of container
   container_name: micontenedormysql
   # dockee image that we use
   image: mysql
   # restar the container
   restart: always
   # ports
   ports:
     - 9090:3306
   # environment
   environment:
     MYSQL_ROOT_PASSWORD: root
     MYSQL_DATABASE: jalaconverter